name: ml_kit_examples
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_ml_kit: ^0.18.0
  google_mlkit_image_labeling: ^0.12.0

  stacked: ^3.4.2
  stacked_services: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  stacked_generator: ^0.7.8


flutter:

 
  uses-material-design: true

